apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-frontend-deployment
  namespace: genie  # Deploy under the genie namespace
spec:
  replicas: 1  # Number of replicas/pods (can be adjusted as needed)
  selector:
    matchLabels:
      app: genie-frontend
  template:
    metadata:
      labels:
        app: genie-frontend
    spec:
      containers:
        - name: genie-frontend
          image: us-central1-docker.pkg.dev/pre-onboarding-427811/genie-backend/genie-frontend:latest  # Replace with your actual image
          ports:
            - containerPort: 80  # Nginx serves on port 80
      nodeSelector:
        role: primary  # Ensuring the deployment runs on nodes with this label
---
apiVersion: v1
kind: Service
metadata:
  name: genie-frontend-services
  namespace: genie  # Deploy the service in the genie namespace
spec:
  selector:
    app: genie-frontend
  ports:
    - name: http  # Added name for the HTTP port
      protocol: TCP
      port: 80
      targetPort: 80  # Container port
    # - name: https  # Added name for the HTTPS port
    #   protocol: TCP
    #   port: 443
    #   targetPort: 443  # Should match your container's SSL listening port (if applicable)
  type: LoadBalancer  # Expose the service externally
  loadBalancerIP: 35.238.73.66
